<?php

namespace Database\Seeders;

use App\Models\DistrictCrime;
use App\Models\Region;
use Illuminate\Database\Seeder;

class DistrictCrimeSeeder extends Seeder
{
    public function run(): void
    {
        // Clear previous test district records
        DistrictCrime::truncate();

        $districts = [
            'karakalpakstan' => [
                [
                    'name' => 'Nukus shahri',
                    'total' => 328,
                    'rate' => 94.3,
                    'light' => 90,
                    'serious' => 72,
                    'v_serious' => 10,
                    'preventable' => 177,
                    'detected' => 137,
                    'cyber' => 14,
                    'solved' => 75.5
                ],
                [
                    'name' => 'Taxiatosh tumani',
                    'total' => 49,
                    'rate' => 63.3,
                    'light' => 11,
                    'serious' => 14,
                    'v_serious' => 2,
                    'preventable' => 25,
                    'detected' => 24,
                    'cyber' => 0,
                    'solved' => 78.4
                ],
                [
                    'name' => 'Amudaryo tumani',
                    'total' => 84,
                    'rate' => 38.9,
                    'light' => 18,
                    'serious' => 20,
                    'v_serious' => 2,
                    'preventable' => 51,
                    'detected' => 29,
                    'cyber' => 0,
                    'solved' => 76.3
                ],
                [
                    'name' => 'Beruniy tumani',
                    'total' => 94,
                    'rate' => 44.5,
                    'light' => 31,
                    'serious' => 27,
                    'v_serious' => 3,
                    'preventable' => 56,
                    'detected' => 0,
                    'cyber' => 2,
                    'solved' => 81.7
                ],
                [
                    'name' => 'Qorao\'zak tumani',
                    'total' => 25,
                    'rate' => 45.8,
                    'light' => 12,
                    'serious' => 5,
                    'v_serious' => 1,
                    'preventable' => 14,
                    'detected' => 10,
                    'cyber' => 0,
                    'solved' => 79.2
                ],
                [
                    'name' => 'Kegeyli tumani',
                    'total' => 30,
                    'rate' => 39.6,
                    'light' => 15,
                    'serious' => 7,
                    'v_serious' => 32,
                    'preventable' => 0,
                    'detected' => 0,
                    'cyber' => 0,
                    'solved' => 80.1
                ],
                [
                    'name' => 'Qo\'ng\'irot tumani',
                    'total' => 95,
                    'rate' => 69.3,
                    'light' => 29,
                    'serious' => 21,
                    'v_serious' => 3,
                    'preventable' => 46,
                    'detected' => 0,
                    'cyber' => 5,
                    'solved' => 80.4
                ],
                [
                    'name' => 'Qonliko\'l tumani',
                    'total' => 25,
                    'rate' => 45.7,
                    'light' => 9,
                    'serious' => 10,
                    'v_serious' => 32,
                    'preventable' => 0,
                    'detected' => 0,
                    'cyber' => 0,
                    'solved' => 82.8
                ],
                [
                    'name' => 'Mo\'ynoq tumani',
                    'total' => 25,
                    'rate' => 73.4,
                    'light' => 12,
                    'serious' => 6,
                    'v_serious' => 32,
                    'preventable' => 0,
                    'detected' => 0,
                    'cyber' => 0,
                    'solved' => 76.7
                ],
                [
                    'name' => 'Nukus tumani',
                    'total' => 38,
                    'rate' => 68.3,
                    'light' => 12,
                    'serious' => 6,
                    'v_serious' => 1,
                    'preventable' => 26,
                    'detected' => 12,
                    'cyber' => 0,
                    'solved' => 79.6
                ],
                [
                    'name' => 'Taxtako\'pir tumani',
                    'total' => 23,
                    'rate' => 59.2,
                    'light' => 8,
                    'serious' => 1,
                    'v_serious' => 1,
                    'preventable' => 13,
                    'detected' => 0,
                    'cyber' => 32,
                    'solved' => 79.6
                ],
                [
                    'name' => 'To\'rtko\'l tumani',
                    'total' => 122,
                    'rate' => 52,
                    'light' => 35,
                    'serious' => 10,
                    'v_serious' => 28,
                    'preventable' => 44,
                    'detected' => 77,
                    'cyber' => 1,
                    'solved' => 75.7
                ],
                [
                    'name' => 'Xo\'jayli tumani',
                    'total' => 78,
                    'rate' => 59.7,
                    'light' => 16,
                    'serious' => 27,
                    'v_serious' => 6,
                    'preventable' => 51,
                    'detected' => 24,
                    'cyber' => 0,
                    'solved' => 79.2
                ],
                [
                    'name' => 'Chimboy tumani',
                    'total' => 38,
                    'rate' => 32.5,
                    'light' => 14,
                    'serious' => 8,
                    'v_serious' => 1,
                    'preventable' => 24,
                    'detected' => 12,
                    'cyber' => 0,
                    'solved' => 78.8
                ],
                [
                    'name' => 'Shumanay tumani',
                    'total' => 13,
                    'rate' => 22.2,
                    'light' => 5,
                    'serious' => 1,
                    'v_serious' => 1,
                    'preventable' => 7,
                    'detected' => 6,
                    'cyber' => 0,
                    'solved' => 82.4
                ],
                [
                    'name' => 'Ellikqal\'a tumani',
                    'total' => 49,
                    'rate' => 27.9,
                    'light' => 20,
                    'serious' => 6,
                    'v_serious' => 6,
                    'preventable' => 24,
                    'detected' => 24,
                    'cyber' => 1,
                    'solved' => 75.4
                ],
                [
                    'name' => 'Bo\'zatov tumani',
                    'total' => 2,
                    'rate' => 9.2,
                    'light' => 32,
                    'serious' => 0,
                    'v_serious' => 32,
                    'preventable' => 0,
                    'detected' => 0,
                    'cyber' => 0,
                    'solved' => 82.1
                ],
            ],
            'khorezm' => [
                [
                    'name' => 'Urganch shahri',
                    'total' => 462,
                    'rate' => 291.7,
                    'light' => 69,
                    'serious' => 208,
                    'v_serious' => 37,
                    'preventable' => 117,
                    'detected' => 246,
                    'cyber' => 99,
                    'solved' => 75.8
                ],
                [
                    'name' => 'Xiva shahri',
                    'total' => 144,
                    'rate' => 142.2,
                    'light' => 25,
                    'serious' => 89,
                    'v_serious' => 5,
                    'preventable' => 19,
                    'detected' => 0,
                    'cyber' => 67,
                    'solved' => 76.7
                ],
                [
                    'name' => 'Gurlan tumani',
                    'total' => 158,
                    'rate' => 97.9,
                    'light' => 15,
                    'serious' => 110,
                    'v_serious' => 2,
                    'preventable' => 21,
                    'detected' => 0,
                    'cyber' => 99,
                    'solved' => 78.1
                ],
                [
                    'name' => 'Shovot tumani',
                    'total' => 145,
                    'rate' => 78.1,
                    'light' => 21,
                    'serious' => 106,
                    'v_serious' => 1,
                    'preventable' => 16,
                    'detected' => 0,
                    'cyber' => 95,
                    'solved' => 78.9
                ],
                [
                    'name' => 'Xonqa tumani',
                    'total' => 211,
                    'rate' => 103.2,
                    'light' => 22,
                    'serious' => 151,
                    'v_serious' => 12,
                    'preventable' => 27,
                    'detected' => 42,
                    'cyber' => 142,
                    'solved' => 78
                ],
                [
                    'name' => 'Xazorasp tumani',
                    'total' => 221,
                    'rate' => 103.8,
                    'light' => 31,
                    'serious' => 144,
                    'v_serious' => 18,
                    'preventable' => 14,
                    'detected' => 68,
                    'cyber' => 139,
                    'solved' => 82.2
                ],
                [
                    'name' => 'Xiva tumani',
                    'total' => 111,
                    'rate' => 69,
                    'light' => 20,
                    'serious' => 71,
                    'v_serious' => 32,
                    'preventable' => 0,
                    'detected' => 0,
                    'cyber' => 0,
                    'solved' => 80.3
                ],
                [
                    'name' => 'Urganch tumani',
                    'total' => 377,
                    'rate' => 169.1,
                    'light' => 36,
                    'serious' => 287,
                    'v_serious' => 11,
                    'preventable' => 52,
                    'detected' => 94,
                    'cyber' => 231,
                    'solved' => 76.3
                ],
                [
                    'name' => 'Qo\'shko\'pir tumani',
                    'total' => 168,
                    'rate' => 89.5,
                    'light' => 25,
                    'serious' => 88,
                    'v_serious' => 28,
                    'preventable' => 17,
                    'detected' => 74,
                    'cyber' => 77,
                    'solved' => 82.9
                ],
                [
                    'name' => 'Bog\'ot tumani',
                    'total' => 175,
                    'rate' => 96,
                    'light' => 21,
                    'serious' => 124,
                    'v_serious' => 7,
                    'preventable' => 14,
                    'detected' => 0,
                    'cyber' => 111,
                    'solved' => 81.5
                ],
                [
                    'name' => 'Yangiariq tumani',
                    'total' => 141,
                    'rate' => 111.3,
                    'light' => 14,
                    'serious' => 108,
                    'v_serious' => 5,
                    'preventable' => 15,
                    'detected' => 0,
                    'cyber' => 94,
                    'solved' => 75.4
                ],
                [
                    'name' => 'Yangibozor tumani',
                    'total' => 108,
                    'rate' => 114,
                    'light' => 21,
                    'serious' => 70,
                    'v_serious' => 1,
                    'preventable' => 23,
                    'detected' => 27,
                    'cyber' => 0,
                    'solved' => 81.9
                ],
                [
                    'name' => 'Tuproqqal\'a tumani',
                    'total' => 94,
                    'rate' => 153,
                    'light' => 21,
                    'serious' => 57,
                    'v_serious' => 5,
                    'preventable' => 15,
                    'detected' => 0,
                    'cyber' => 47,
                    'solved' => 82.3
                ],
            ],
            'kashkadarya' => [
                [
                    'name' => 'Qarshi shahri',
                    'total' => 1038,
                    'rate' => 339,
                    'light' => 144,
                    'serious' => 659,
                    'v_serious' => 30,
                    'preventable' => 196,
                    'detected' => 273,
                    'cyber' => 569,
                    'solved' => 79
                ],
                [
                    'name' => 'Qarshi tumani',
                    'total' => 493,
                    'rate' => 173.2,
                    'light' => 57,
                    'serious' => 352,
                    'v_serious' => 13,
                    'preventable' => 87,
                    'detected' => 75,
                    'cyber' => 331,
                    'solved' => 78.9
                ],
                [
                    'name' => 'G\'uzor tumani',
                    'total' => 426,
                    'rate' => 185.6,
                    'light' => 47,
                    'serious' => 324,
                    'v_serious' => 5,
                    'preventable' => 63,
                    'detected' => 62,
                    'cyber' => 301,
                    'solved' => 75.3
                ],
                [
                    'name' => 'Koson tumani',
                    'total' => 413,
                    'rate' => 127.1,
                    'light' => 60,
                    'serious' => 283,
                    'v_serious' => 11,
                    'preventable' => 70,
                    'detected' => 88,
                    'cyber' => 255,
                    'solved' => 79.2
                ],
                [
                    'name' => 'Yakkabog\' tumani',
                    'total' => 347,
                    'rate' => 119.5,
                    'light' => 40,
                    'serious' => 260,
                    'v_serious' => 3,
                    'preventable' => 60,
                    'detected' => 45,
                    'cyber' => 242,
                    'solved' => 76.8
                ],
                [
                    'name' => 'Shahrisabz tumani',
                    'total' => 279,
                    'rate' => 116.3,
                    'light' => 38,
                    'serious' => 194,
                    'v_serious' => 7,
                    'preventable' => 51,
                    'detected' => 41,
                    'cyber' => 187,
                    'solved' => 82.1
                ],
                [
                    'name' => 'Chiroqchi tumani',
                    'total' => 328,
                    'rate' => 117.9,
                    'light' => 52,
                    'serious' => 236,
                    'v_serious' => 4,
                    'preventable' => 56,
                    'detected' => 52,
                    'cyber' => 220,
                    'solved' => 81.2
                ],
                [
                    'name' => 'Qamashi tumani',
                    'total' => 348,
                    'rate' => 114.9,
                    'light' => 34,
                    'serious' => 265,
                    'v_serious' => 3,
                    'preventable' => 48,
                    'detected' => 48,
                    'cyber' => 252,
                    'solved' => 80.5
                ],
                [
                    'name' => 'Kitob tumani',
                    'total' => 419,
                    'rate' => 144.5,
                    'light' => 43,
                    'serious' => 311,
                    'v_serious' => 3,
                    'preventable' => 50,
                    'detected' => 0,
                    'cyber' => 309,
                    'solved' => 75.6
                ],
                [
                    'name' => 'Kasbi tumani',
                    'total' => 249,
                    'rate' => 112.8,
                    'light' => 23,
                    'serious' => 194,
                    'v_serious' => 4,
                    'preventable' => 30,
                    'detected' => 28,
                    'cyber' => 191,
                    'solved' => 79.7
                ],
                [
                    'name' => 'Dehqonobod tumani',
                    'total' => 211,
                    'rate' => 128.1,
                    'light' => 22,
                    'serious' => 168,
                    'v_serious' => 4,
                    'preventable' => 20,
                    'detected' => 30,
                    'cyber' => 161,
                    'solved' => 79.2
                ],
                [
                    'name' => 'Nishon tumani',
                    'total' => 262,
                    'rate' => 151,
                    'light' => 37,
                    'serious' => 205,
                    'v_serious' => 3,
                    'preventable' => 25,
                    'detected' => 44,
                    'cyber' => 193,
                    'solved' => 82.1
                ],
                [
                    'name' => 'Mirishkor tumani',
                    'total' => 143,
                    'rate' => 106.5,
                    'light' => 25,
                    'serious' => 99,
                    'v_serious' => 4,
                    'preventable' => 30,
                    'detected' => 26,
                    'cyber' => 87,
                    'solved' => 78.7
                ],
                [
                    'name' => 'Muborak tumani',
                    'total' => 150,
                    'rate' => 154.1,
                    'light' => 23,
                    'serious' => 98,
                    'v_serious' => 5,
                    'preventable' => 25,
                    'detected' => 33,
                    'cyber' => 92,
                    'solved' => 80.1
                ],
                [
                    'name' => 'Ko\'kdala tumani',
                    'total' => 295,
                    'rate' => 148.4,
                    'light' => 38,
                    'serious' => 198,
                    'v_serious' => 11,
                    'preventable' => 54,
                    'detected' => 55,
                    'cyber' => 186,
                    'solved' => 75.5
                ],
                [
                    'name' => 'Shahrisabz shahri',
                    'total' => 342,
                    'rate' => 225.1,
                    'light' => 45,
                    'serious' => 231,
                    'v_serious' => 10,
                    'preventable' => 64,
                    'detected' => 71,
                    'cyber' => 207,
                    'solved' => 80.5
                ],
            ],
            'surkhandarya' => [
                [
                    'name' => 'Termiz shahri',
                    'total' => 326,
                    'rate' => 152.8,
                    'light' => 78,
                    'serious' => 87,
                    'v_serious' => 44,
                    'preventable' => 110,
                    'detected' => 198,
                    'cyber' => 18,
                    'solved' => 77.7
                ],
                [
                    'name' => 'Angor tumani',
                    'total' => 86,
                    'rate' => 57.6,
                    'light' => 18,
                    'serious' => 20,
                    'v_serious' => 11,
                    'preventable' => 44,
                    'detected' => 40,
                    'cyber' => 2,
                    'solved' => 76.4
                ],
                [
                    'name' => 'Bandixon tumani',
                    'total' => 27,
                    'rate' => 31.1,
                    'light' => 8,
                    'serious' => 10,
                    'v_serious' => 32,
                    'preventable' => 0,
                    'detected' => 0,
                    'cyber' => 0,
                    'solved' => 78.8
                ],
                [
                    'name' => 'Boysun tumani',
                    'total' => 63,
                    'rate' => 49.1,
                    'light' => 25,
                    'serious' => 11,
                    'v_serious' => 7,
                    'preventable' => 30,
                    'detected' => 0,
                    'cyber' => 3,
                    'solved' => 76.2
                ],
                [
                    'name' => 'Denov tumani',
                    'total' => 393,
                    'rate' => 89.6,
                    'light' => 87,
                    'serious' => 180,
                    'v_serious' => 24,
                    'preventable' => 112,
                    'detected' => 144,
                    'cyber' => 137,
                    'solved' => 78.2
                ],
                [
                    'name' => 'Jarqo\'rg\'on tumani',
                    'total' => 128,
                    'rate' => 51.7,
                    'light' => 47,
                    'serious' => 35,
                    'v_serious' => 7,
                    'preventable' => 44,
                    'detected' => 81,
                    'cyber' => 3,
                    'solved' => 78.5
                ],
                [
                    'name' => 'Muzrabot tumani',
                    'total' => 79,
                    'rate' => 49.7,
                    'light' => 24,
                    'serious' => 36,
                    'v_serious' => 2,
                    'preventable' => 28,
                    'detected' => 0,
                    'cyber' => 22,
                    'solved' => 76.2
                ],
                [
                    'name' => 'Oltinsoy tumani',
                    'total' => 103,
                    'rate' => 51.5,
                    'light' => 20,
                    'serious' => 59,
                    'v_serious' => 2,
                    'preventable' => 30,
                    'detected' => 0,
                    'cyber' => 42,
                    'solved' => 78.9
                ],
                [
                    'name' => 'Sariosiyo tumani',
                    'total' => 148,
                    'rate' => 62.6,
                    'light' => 40,
                    'serious' => 60,
                    'v_serious' => 13,
                    'preventable' => 38,
                    'detected' => 81,
                    'cyber' => 29,
                    'solved' => 75
                ],
                [
                    'name' => 'Termiz tumani',
                    'total' => 135,
                    'rate' => 151,
                    'light' => 30,
                    'serious' => 38,
                    'v_serious' => 49,
                    'preventable' => 24,
                    'detected' => 102,
                    'cyber' => 9,
                    'solved' => 75.3
                ],
                [
                    'name' => 'Uzun tumani',
                    'total' => 63,
                    'rate' => 32.3,
                    'light' => 24,
                    'serious' => 21,
                    'v_serious' => 3,
                    'preventable' => 26,
                    'detected' => 0,
                    'cyber' => 9,
                    'solved' => 81.3
                ],
                [
                    'name' => 'Sherobod tumani',
                    'total' => 66,
                    'rate' => 30.4,
                    'light' => 24,
                    'serious' => 15,
                    'v_serious' => 3,
                    'preventable' => 35,
                    'detected' => 29,
                    'cyber' => 2,
                    'solved' => 82.7
                ],
                [
                    'name' => 'Sho\'rchi tumani',
                    'total' => 94,
                    'rate' => 39.5,
                    'light' => 25,
                    'serious' => 30,
                    'v_serious' => 9,
                    'preventable' => 50,
                    'detected' => 42,
                    'cyber' => 2,
                    'solved' => 78.1
                ],
                [
                    'name' => 'Qiziriq tumani',
                    'total' => 29,
                    'rate' => 22.5,
                    'light' => 10,
                    'serious' => 4,
                    'v_serious' => 1,
                    'preventable' => 13,
                    'detected' => 0,
                    'cyber' => 32,
                    'solved' => 75.8
                ],
                [
                    'name' => 'Qumqo\'rg\'on tumani',
                    'total' => 100,
                    'rate' => 37.8,
                    'light' => 22,
                    'serious' => 43,
                    'v_serious' => 3,
                    'preventable' => 35,
                    'detected' => 0,
                    'cyber' => 33,
                    'solved' => 77
                ],
            ],
            'namangan' => [
                [
                    'name' => 'Namangan shahri',
                    'total' => 441,
                    'rate' => 112.4,
                    'light' => 109,
                    'serious' => 112,
                    'v_serious' => 32,
                    'preventable' => 225,
                    'detected' => 185,
                    'cyber' => 31,
                    'solved' => 77.5
                ],
                [
                    'name' => 'Mingbuloq tumani',
                    'total' => 104,
                    'rate' => 73.4,
                    'light' => 36,
                    'serious' => 25,
                    'v_serious' => 8,
                    'preventable' => 27,
                    'detected' => 72,
                    'cyber' => 5,
                    'solved' => 80.5
                ],
                [
                    'name' => 'Kosonsoy tumani',
                    'total' => 120,
                    'rate' => 50.6,
                    'light' => 37,
                    'serious' => 24,
                    'v_serious' => 5,
                    'preventable' => 39,
                    'detected' => 74,
                    'cyber' => 7,
                    'solved' => 81.4
                ],
                [
                    'name' => 'Namangan tumani',
                    'total' => 126,
                    'rate' => 62.8,
                    'light' => 25,
                    'serious' => 38,
                    'v_serious' => 8,
                    'preventable' => 45,
                    'detected' => 70,
                    'cyber' => 11,
                    'solved' => 81.1
                ],
                [
                    'name' => 'Norin tumani',
                    'total' => 114,
                    'rate' => 62.9,
                    'light' => 40,
                    'serious' => 30,
                    'v_serious' => 3,
                    'preventable' => 49,
                    'detected' => 57,
                    'cyber' => 8,
                    'solved' => 76.1
                ],
                [
                    'name' => 'Pop tumani',
                    'total' => 257,
                    'rate' => 106,
                    'light' => 67,
                    'serious' => 53,
                    'v_serious' => 27,
                    'preventable' => 114,
                    'detected' => 128,
                    'cyber' => 15,
                    'solved' => 75.7
                ],
                [
                    'name' => 'To\'raqo\'rg\'on tumani',
                    'total' => 195,
                    'rate' => 76.6,
                    'light' => 53,
                    'serious' => 42,
                    'v_serious' => 5,
                    'preventable' => 71,
                    'detected' => 98,
                    'cyber' => 26,
                    'solved' => 79.4
                ],
                [
                    'name' => 'Uychi tumani',
                    'total' => 159,
                    'rate' => 65.8,
                    'light' => 37,
                    'serious' => 45,
                    'v_serious' => 9,
                    'preventable' => 90,
                    'detected' => 64,
                    'cyber' => 5,
                    'solved' => 82.6
                ],
                [
                    'name' => 'Uchqo\'rg\'on tumani',
                    'total' => 135,
                    'rate' => 70.8,
                    'light' => 44,
                    'serious' => 25,
                    'v_serious' => 4,
                    'preventable' => 47,
                    'detected' => 84,
                    'cyber' => 4,
                    'solved' => 77.3
                ],
                [
                    'name' => 'Chust tumani',
                    'total' => 255,
                    'rate' => 86.7,
                    'light' => 62,
                    'serious' => 61,
                    'v_serious' => 24,
                    'preventable' => 105,
                    'detected' => 129,
                    'cyber' => 21,
                    'solved' => 79
                ],
                [
                    'name' => 'Chortoq tumani',
                    'total' => 161,
                    'rate' => 72.4,
                    'light' => 35,
                    'serious' => 38,
                    'v_serious' => 10,
                    'preventable' => 70,
                    'detected' => 88,
                    'cyber' => 3,
                    'solved' => 78.9
                ],
                [
                    'name' => 'Yangiqo\'rg\'on tumani',
                    'total' => 145,
                    'rate' => 59,
                    'light' => 42,
                    'serious' => 37,
                    'v_serious' => 4,
                    'preventable' => 63,
                    'detected' => 70,
                    'cyber' => 12,
                    'solved' => 79.1
                ],
                [
                    'name' => 'Davlatobod tumani',
                    'total' => 325,
                    'rate' => 196.4,
                    'light' => 77,
                    'serious' => 74,
                    'v_serious' => 20,
                    'preventable' => 123,
                    'detected' => 191,
                    'cyber' => 11,
                    'solved' => 81.8
                ],
                [
                    'name' => 'Yangi Namangan tumani',
                    'total' => 269,
                    'rate' => 159,
                    'light' => 54,
                    'serious' => 55,
                    'v_serious' => 12,
                    'preventable' => 113,
                    'detected' => 149,
                    'cyber' => 7,
                    'solved' => 82.1
                ],
            ],
            'andijan' => [
                [
                    'name' => 'Andijon shahri',
                    'total' => 768,
                    'rate' => 152.7,
                    'light' => 197,
                    'serious' => 272,
                    'v_serious' => 50,
                    'preventable' => 341,
                    'detected' => 373,
                    'cyber' => 54,
                    'solved' => 80.8
                ],
                [
                    'name' => 'Andijon tumani',
                    'total' => 193,
                    'rate' => 64.7,
                    'light' => 57,
                    'serious' => 55,
                    'v_serious' => 14,
                    'preventable' => 72,
                    'detected' => 89,
                    'cyber' => 32,
                    'solved' => 79.6
                ],
                [
                    'name' => 'Asaka tumani',
                    'total' => 283,
                    'rate' => 77,
                    'light' => 76,
                    'serious' => 106,
                    'v_serious' => 19,
                    'preventable' => 89,
                    'detected' => 127,
                    'cyber' => 67,
                    'solved' => 76.9
                ],
                [
                    'name' => 'Baliqchi tumani',
                    'total' => 131,
                    'rate' => 58.8,
                    'light' => 36,
                    'serious' => 40,
                    'v_serious' => 7,
                    'preventable' => 44,
                    'detected' => 71,
                    'cyber' => 16,
                    'solved' => 77.6
                ],
                [
                    'name' => 'Bo\'ston tumani',
                    'total' => 54,
                    'rate' => 66.7,
                    'light' => 16,
                    'serious' => 12,
                    'v_serious' => 10,
                    'preventable' => 20,
                    'detected' => 34,
                    'cyber' => 32,
                    'solved' => 75.5
                ],
                [
                    'name' => 'Buloqboshi tumani',
                    'total' => 83,
                    'rate' => 52.5,
                    'light' => 24,
                    'serious' => 16,
                    'v_serious' => 4,
                    'preventable' => 18,
                    'detected' => 62,
                    'cyber' => 3,
                    'solved' => 79.9
                ],
                [
                    'name' => 'Jalaquduq tumani',
                    'total' => 101,
                    'rate' => 49.4,
                    'light' => 20,
                    'serious' => 33,
                    'v_serious' => 4,
                    'preventable' => 27,
                    'detected' => 66,
                    'cyber' => 8,
                    'solved' => 78.9
                ],
                [
                    'name' => 'Izboskan tumani',
                    'total' => 182,
                    'rate' => 68.9,
                    'light' => 37,
                    'serious' => 41,
                    'v_serious' => 16,
                    'preventable' => 55,
                    'detected' => 107,
                    'cyber' => 20,
                    'solved' => 75.5
                ],
                [
                    'name' => 'Qo\'rg\'ontepa tumani',
                    'total' => 149,
                    'rate' => 62.8,
                    'light' => 33,
                    'serious' => 39,
                    'v_serious' => 9,
                    'preventable' => 63,
                    'detected' => 83,
                    'cyber' => 3,
                    'solved' => 77.1
                ],
                [
                    'name' => 'Marhamat tumani',
                    'total' => 155,
                    'rate' => 80.5,
                    'light' => 23,
                    'serious' => 63,
                    'v_serious' => 18,
                    'preventable' => 43,
                    'detected' => 76,
                    'cyber' => 36,
                    'solved' => 76.2
                ],
                [
                    'name' => 'Oltinko\'l tumani',
                    'total' => 130,
                    'rate' => 66.3,
                    'light' => 40,
                    'serious' => 23,
                    'v_serious' => 9,
                    'preventable' => 42,
                    'detected' => 87,
                    'cyber' => 1,
                    'solved' => 76.1
                ],
                [
                    'name' => 'Paxtaobod tumani',
                    'total' => 142,
                    'rate' => 65.9,
                    'light' => 35,
                    'serious' => 30,
                    'v_serious' => 17,
                    'preventable' => 53,
                    'detected' => 86,
                    'cyber' => 3,
                    'solved' => 79.4
                ],
                [
                    'name' => 'Ulug\'nor tumani',
                    'total' => 65,
                    'rate' => 100.8,
                    'light' => 24,
                    'serious' => 12,
                    'v_serious' => 1,
                    'preventable' => 21,
                    'detected' => 0,
                    'cyber' => 3,
                    'solved' => 79.8
                ],
                [
                    'name' => 'Xonobod shahri',
                    'total' => 39,
                    'rate' => 83.1,
                    'light' => 9,
                    'serious' => 9,
                    'v_serious' => 6,
                    'preventable' => 10,
                    'detected' => 28,
                    'cyber' => 1,
                    'solved' => 79.8
                ],
                [
                    'name' => 'Xo\'jaobod tumani',
                    'total' => 152,
                    'rate' => 122.4,
                    'light' => 34,
                    'serious' => 47,
                    'v_serious' => 20,
                    'preventable' => 46,
                    'detected' => 104,
                    'cyber' => 2,
                    'solved' => 79.6
                ],
                [
                    'name' => 'Shahrixon tumani',
                    'total' => 183,
                    'rate' => 54.4,
                    'light' => 54,
                    'serious' => 48,
                    'v_serious' => 14,
                    'preventable' => 79,
                    'detected' => 97,
                    'cyber' => 7,
                    'solved' => 79
                ],
            ],
            'fergana' => [
                [
                    'name' => 'Farg\'ona shahri',
                    'total' => 955,
                    'rate' => 284.1,
                    'light' => 165,
                    'serious' => 279,
                    'v_serious' => 48,
                    'preventable' => 408,
                    'detected' => 465,
                    'cyber' => 82,
                    'solved' => 82.1
                ],
                [
                    'name' => 'Qo\'qon shahri',
                    'total' => 703,
                    'rate' => 220.4,
                    'light' => 126,
                    'serious' => 214,
                    'v_serious' => 67,
                    'preventable' => 244,
                    'detected' => 396,
                    'cyber' => 63,
                    'solved' => 82.2
                ],
                [
                    'name' => 'Marg\'ilon shahri',
                    'total' => 301,
                    'rate' => 115.1,
                    'light' => 70,
                    'serious' => 59,
                    'v_serious' => 19,
                    'preventable' => 116,
                    'detected' => 171,
                    'cyber' => 14,
                    'solved' => 82
                ],
                [
                    'name' => 'Quvasoy shahri',
                    'total' => 96,
                    'rate' => 91.7,
                    'light' => 27,
                    'serious' => 30,
                    'v_serious' => 14,
                    'preventable' => 36,
                    'detected' => 58,
                    'cyber' => 2,
                    'solved' => 82.5
                ],
                [
                    'name' => 'Oltiariq tumani',
                    'total' => 251,
                    'rate' => 106.2,
                    'light' => 55,
                    'serious' => 63,
                    'v_serious' => 12,
                    'preventable' => 134,
                    'detected' => 103,
                    'cyber' => 14,
                    'solved' => 76.1
                ],
                [
                    'name' => 'Qo\'shtepa tumani',
                    'total' => 155,
                    'rate' => 71.3,
                    'light' => 51,
                    'serious' => 35,
                    'v_serious' => 4,
                    'preventable' => 56,
                    'detected' => 0,
                    'cyber' => 12,
                    'solved' => 80.6
                ],
                [
                    'name' => 'Beshariq tumani',
                    'total' => 126,
                    'rate' => 50.5,
                    'light' => 35,
                    'serious' => 31,
                    'v_serious' => 8,
                    'preventable' => 58,
                    'detected' => 64,
                    'cyber' => 4,
                    'solved' => 81.9
                ],
                [
                    'name' => 'Quva tumani',
                    'total' => 180,
                    'rate' => 63.2,
                    'light' => 54,
                    'serious' => 36,
                    'v_serious' => 6,
                    'preventable' => 86,
                    'detected' => 0,
                    'cyber' => 9,
                    'solved' => 77
                ],
                [
                    'name' => 'Uchko\'prik tumani',
                    'total' => 181,
                    'rate' => 72.1,
                    'light' => 46,
                    'serious' => 54,
                    'v_serious' => 11,
                    'preventable' => 75,
                    'detected' => 82,
                    'cyber' => 24,
                    'solved' => 78.8
                ],
                [
                    'name' => 'O\'zbekiston tumani',
                    'total' => 178,
                    'rate' => 73.1,
                    'light' => 54,
                    'serious' => 53,
                    'v_serious' => 4,
                    'preventable' => 75,
                    'detected' => 81,
                    'cyber' => 22,
                    'solved' => 75.2
                ],
                [
                    'name' => 'Farg\'ona tumani',
                    'total' => 245,
                    'rate' => 106.7,
                    'light' => 58,
                    'serious' => 73,
                    'v_serious' => 7,
                    'preventable' => 96,
                    'detected' => 128,
                    'cyber' => 21,
                    'solved' => 75.3
                ],
                [
                    'name' => 'Bag\'dod tumani',
                    'total' => 136,
                    'rate' => 56.4,
                    'light' => 35,
                    'serious' => 35,
                    'v_serious' => 8,
                    'preventable' => 58,
                    'detected' => 75,
                    'cyber' => 3,
                    'solved' => 82.6
                ],
                [
                    'name' => 'Rishton tumani',
                    'total' => 109,
                    'rate' => 48.7,
                    'light' => 30,
                    'serious' => 29,
                    'v_serious' => 2,
                    'preventable' => 31,
                    'detected' => 75,
                    'cyber' => 3,
                    'solved' => 80.9
                ],
                [
                    'name' => 'Dang\'ara tumani',
                    'total' => 147,
                    'rate' => 80,
                    'light' => 38,
                    'serious' => 24,
                    'v_serious' => 6,
                    'preventable' => 75,
                    'detected' => 67,
                    'cyber' => 5,
                    'solved' => 80.7
                ],
                [
                    'name' => 'Toshloq tumani',
                    'total' => 120,
                    'rate' => 53.2,
                    'light' => 40,
                    'serious' => 23,
                    'v_serious' => 4,
                    'preventable' => 55,
                    'detected' => 58,
                    'cyber' => 7,
                    'solved' => 81.6
                ],
                [
                    'name' => 'Buvaida tumani',
                    'total' => 132,
                    'rate' => 51.5,
                    'light' => 31,
                    'serious' => 28,
                    'v_serious' => 10,
                    'preventable' => 43,
                    'detected' => 74,
                    'cyber' => 15,
                    'solved' => 81.3
                ],
                [
                    'name' => 'Yozyovon tumani',
                    'total' => 101,
                    'rate' => 81.4,
                    'light' => 22,
                    'serious' => 28,
                    'v_serious' => 4,
                    'preventable' => 34,
                    'detected' => 54,
                    'cyber' => 13,
                    'solved' => 75.4
                ],
                [
                    'name' => 'So\'x tumani',
                    'total' => 28,
                    'rate' => 31.4,
                    'light' => 5,
                    'serious' => 8,
                    'v_serious' => 1,
                    'preventable' => 7,
                    'detected' => 0,
                    'cyber' => 6,
                    'solved' => 75.3
                ],
                [
                    'name' => 'Furqat tumani',
                    'total' => 113,
                    'rate' => 85.9,
                    'light' => 26,
                    'serious' => 37,
                    'v_serious' => 1,
                    'preventable' => 33,
                    'detected' => 0,
                    'cyber' => 24,
                    'solved' => 79.9
                ],
            ],
            'navoi' => [
                [
                    'name' => 'Navoiy shahri',
                    'total' => 348,
                    'rate' => 203.6,
                    'light' => 112,
                    'serious' => 91,
                    'v_serious' => 25,
                    'preventable' => 137,
                    'detected' => 204,
                    'cyber' => 7,
                    'solved' => 75.7
                ],
                [
                    'name' => 'Zarafshon shahri',
                    'total' => 70,
                    'rate' => 76.2,
                    'light' => 22,
                    'serious' => 15,
                    'v_serious' => 8,
                    'preventable' => 24,
                    'detected' => 46,
                    'cyber' => 32,
                    'solved' => 77.4
                ],
                [
                    'name' => 'Uchquduq tumani',
                    'total' => 56,
                    'rate' => 141.5,
                    'light' => 24,
                    'serious' => 15,
                    'v_serious' => 3,
                    'preventable' => 16,
                    'detected' => 40,
                    'cyber' => 32,
                    'solved' => 81.8
                ],
                [
                    'name' => 'Karmana tumani',
                    'total' => 204,
                    'rate' => 142.3,
                    'light' => 55,
                    'serious' => 51,
                    'v_serious' => 9,
                    'preventable' => 72,
                    'detected' => 121,
                    'cyber' => 11,
                    'solved' => 76.1
                ],
                [
                    'name' => 'Konimex tumani',
                    'total' => 58,
                    'rate' => 158.3,
                    'light' => 25,
                    'serious' => 11,
                    'v_serious' => 5,
                    'preventable' => 19,
                    'detected' => 38,
                    'cyber' => 1,
                    'solved' => 78.9
                ],
                [
                    'name' => 'Qiziltepa tumani',
                    'total' => 105,
                    'rate' => 63.3,
                    'light' => 39,
                    'serious' => 15,
                    'v_serious' => 6,
                    'preventable' => 33,
                    'detected' => 70,
                    'cyber' => 2,
                    'solved' => 80
                ],
                [
                    'name' => 'Tomdi tumani',
                    'total' => 46,
                    'rate' => 303.1,
                    'light' => 25,
                    'serious' => 6,
                    'v_serious' => 2,
                    'preventable' => 18,
                    'detected' => 28,
                    'cyber' => 32,
                    'solved' => 75.9
                ],
                [
                    'name' => 'Navbahor tumani',
                    'total' => 133,
                    'rate' => 108.2,
                    'light' => 59,
                    'serious' => 21,
                    'v_serious' => 5,
                    'preventable' => 53,
                    'detected' => 78,
                    'cyber' => 2,
                    'solved' => 78.4
                ],
                [
                    'name' => 'Nurota tumani',
                    'total' => 86,
                    'rate' => 94.5,
                    'light' => 38,
                    'serious' => 11,
                    'v_serious' => 3,
                    'preventable' => 32,
                    'detected' => 53,
                    'cyber' => 1,
                    'solved' => 75.4
                ],
                [
                    'name' => 'Xatirchi tumani',
                    'total' => 182,
                    'rate' => 84,
                    'light' => 53,
                    'serious' => 37,
                    'v_serious' => 13,
                    'preventable' => 90,
                    'detected' => 85,
                    'cyber' => 7,
                    'solved' => 76.4
                ],
                [
                    'name' => 'G\'ozg\'on shahri',
                    'total' => 9,
                    'rate' => 95.9,
                    'light' => 6,
                    'serious' => 2,
                    'v_serious' => 32,
                    'preventable' => 0,
                    'detected' => 0,
                    'cyber' => 0,
                    'solved' => 81.1
                ],
            ],
            'bukhara' => [
                [
                    'name' => 'Buxoro shahri',
                    'total' => 667,
                    'rate' => 217.4,
                    'light' => 170,
                    'serious' => 195,
                    'v_serious' => 34,
                    'preventable' => 267,
                    'detected' => 355,
                    'cyber' => 45,
                    'solved' => 82.7
                ],
                [
                    'name' => 'Kogon shahri',
                    'total' => 104,
                    'rate' => 157.8,
                    'light' => 23,
                    'serious' => 25,
                    'v_serious' => 14,
                    'preventable' => 29,
                    'detected' => 65,
                    'cyber' => 10,
                    'solved' => 76.1
                ],
                [
                    'name' => 'Kogon tumani',
                    'total' => 88,
                    'rate' => 100.4,
                    'light' => 31,
                    'serious' => 19,
                    'v_serious' => 7,
                    'preventable' => 31,
                    'detected' => 50,
                    'cyber' => 7,
                    'solved' => 80.2
                ],
                [
                    'name' => 'Buxoro tumani',
                    'total' => 154,
                    'rate' => 83.5,
                    'light' => 49,
                    'serious' => 35,
                    'v_serious' => 7,
                    'preventable' => 48,
                    'detected' => 100,
                    'cyber' => 6,
                    'solved' => 77.8
                ],
                [
                    'name' => 'Vobkent tumani',
                    'total' => 80,
                    'rate' => 52.2,
                    'light' => 26,
                    'serious' => 14,
                    'v_serious' => 1,
                    'preventable' => 19,
                    'detected' => 0,
                    'cyber' => 3,
                    'solved' => 77.9
                ],
                [
                    'name' => 'G\'ijduvon tumani',
                    'total' => 260,
                    'rate' => 78.9,
                    'light' => 66,
                    'serious' => 86,
                    'v_serious' => 11,
                    'preventable' => 89,
                    'detected' => 155,
                    'cyber' => 16,
                    'solved' => 76.6
                ],
                [
                    'name' => 'Qorako\'l tumani',
                    'total' => 127,
                    'rate' => 73.1,
                    'light' => 42,
                    'serious' => 36,
                    'v_serious' => 6,
                    'preventable' => 26,
                    'detected' => 94,
                    'cyber' => 7,
                    'solved' => 77.1
                ],
                [
                    'name' => 'Romitan tumani',
                    'total' => 91,
                    'rate' => 58.8,
                    'light' => 38,
                    'serious' => 20,
                    'v_serious' => 3,
                    'preventable' => 16,
                    'detected' => 69,
                    'cyber' => 6,
                    'solved' => 78.4
                ],
                [
                    'name' => 'Jondor tumani',
                    'total' => 122,
                    'rate' => 63.8,
                    'light' => 62,
                    'serious' => 27,
                    'v_serious' => 3,
                    'preventable' => 34,
                    'detected' => 85,
                    'cyber' => 3,
                    'solved' => 80.9
                ],
                [
                    'name' => 'Shofirkon tumani',
                    'total' => 144,
                    'rate' => 76.4,
                    'light' => 40,
                    'serious' => 46,
                    'v_serious' => 11,
                    'preventable' => 38,
                    'detected' => 96,
                    'cyber' => 10,
                    'solved' => 82.7
                ],
                [
                    'name' => 'Olot tumani',
                    'total' => 82,
                    'rate' => 77.3,
                    'light' => 37,
                    'serious' => 13,
                    'v_serious' => 2,
                    'preventable' => 24,
                    'detected' => 0,
                    'cyber' => 4,
                    'solved' => 75.7
                ],
                [
                    'name' => 'Peshku tumani',
                    'total' => 81,
                    'rate' => 59.9,
                    'light' => 28,
                    'serious' => 19,
                    'v_serious' => 3,
                    'preventable' => 14,
                    'detected' => 0,
                    'cyber' => 9,
                    'solved' => 76.1
                ],
                [
                    'name' => 'Qorovulbozor tumani',
                    'total' => 53,
                    'rate' => 257.4,
                    'light' => 26,
                    'serious' => 7,
                    'v_serious' => 3,
                    'preventable' => 19,
                    'detected' => 33,
                    'cyber' => 1,
                    'solved' => 80.9
                ],
            ],
            'jizzakh' => [
                [
                    'name' => 'Jizzax shahri',
                    'total' => 731,
                    'rate' => 358.9,
                    'light' => 87,
                    'serious' => 475,
                    'v_serious' => 12,
                    'preventable' => 98,
                    'detected' => 235,
                    'cyber' => 398,
                    'solved' => 82.9
                ],
                [
                    'name' => 'Sharof Rashidov tumani',
                    'total' => 444,
                    'rate' => 174.8,
                    'light' => 43,
                    'serious' => 304,
                    'v_serious' => 9,
                    'preventable' => 77,
                    'detected' => 90,
                    'cyber' => 277,
                    'solved' => 77.3
                ],
                [
                    'name' => 'Arnasoy tumani',
                    'total' => 77,
                    'rate' => 154.9,
                    'light' => 9,
                    'serious' => 55,
                    'v_serious' => 1,
                    'preventable' => 11,
                    'detected' => 0,
                    'cyber' => 53,
                    'solved' => 78
                ],
                [
                    'name' => 'Baxmal tumani',
                    'total' => 151,
                    'rate' => 85.8,
                    'light' => 19,
                    'serious' => 112,
                    'v_serious' => 8,
                    'preventable' => 21,
                    'detected' => 34,
                    'cyber' => 96,
                    'solved' => 78.5
                ],
                [
                    'name' => 'G\'allaorol tumani',
                    'total' => 203,
                    'rate' => 105.8,
                    'light' => 25,
                    'serious' => 132,
                    'v_serious' => 7,
                    'preventable' => 34,
                    'detected' => 62,
                    'cyber' => 107,
                    'solved' => 82
                ],
                [
                    'name' => 'Do\'stlik tumani',
                    'total' => 101,
                    'rate' => 142.1,
                    'light' => 10,
                    'serious' => 71,
                    'v_serious' => 3,
                    'preventable' => 9,
                    'detected' => 0,
                    'cyber' => 58,
                    'solved' => 81.9
                ],
                [
                    'name' => 'Zarbdor tumani',
                    'total' => 122,
                    'rate' => 125.3,
                    'light' => 10,
                    'serious' => 87,
                    'v_serious' => 3,
                    'preventable' => 17,
                    'detected' => 30,
                    'cyber' => 75,
                    'solved' => 79.8
                ],
                [
                    'name' => 'Zafarobod tumani',
                    'total' => 58,
                    'rate' => 105.8,
                    'light' => 6,
                    'serious' => 39,
                    'v_serious' => 2,
                    'preventable' => 4,
                    'detected' => 0,
                    'cyber' => 33,
                    'solved' => 81.2
                ],
                [
                    'name' => 'Zomin tumani',
                    'total' => 207,
                    'rate' => 111,
                    'light' => 33,
                    'serious' => 144,
                    'v_serious' => 8,
                    'preventable' => 39,
                    'detected' => 50,
                    'cyber' => 118,
                    'solved' => 75.1
                ],
                [
                    'name' => 'Mirzacho\'l tumani',
                    'total' => 79,
                    'rate' => 139.7,
                    'light' => 10,
                    'serious' => 54,
                    'v_serious' => 3,
                    'preventable' => 8,
                    'detected' => 23,
                    'cyber' => 48,
                    'solved' => 80
                ],
                [
                    'name' => 'Paxtakor tumani',
                    'total' => 108,
                    'rate' => 130.2,
                    'light' => 19,
                    'serious' => 64,
                    'v_serious' => 6,
                    'preventable' => 15,
                    'detected' => 43,
                    'cyber' => 50,
                    'solved' => 82
                ],
                [
                    'name' => 'Forish tumani',
                    'total' => 106,
                    'rate' => 105.7,
                    'light' => 20,
                    'serious' => 67,
                    'v_serious' => 32,
                    'preventable' => 0,
                    'detected' => 0,
                    'cyber' => 0,
                    'solved' => 80.3
                ],
                [
                    'name' => 'Yangiobod tumani',
                    'total' => 39,
                    'rate' => 129.5,
                    'light' => 7,
                    'serious' => 27,
                    'v_serious' => 1,
                    'preventable' => 32,
                    'detected' => 0,
                    'cyber' => 25,
                    'solved' => 75.7
                ],
            ],
            'syrdarya' => [
                [
                    'name' => 'Guliston shahri',
                    'total' => 238,
                    'rate' => 229,
                    'light' => 66,
                    'serious' => 73,
                    'v_serious' => 7,
                    'preventable' => 92,
                    'detected' => 136,
                    'cyber' => 10,
                    'solved' => 77.8
                ],
                [
                    'name' => 'Sirdaryo tumani',
                    'total' => 168,
                    'rate' => 119.8,
                    'light' => 49,
                    'serious' => 42,
                    'v_serious' => 9,
                    'preventable' => 42,
                    'detected' => 122,
                    'cyber' => 4,
                    'solved' => 78.6
                ],
                [
                    'name' => 'Shirin shahri',
                    'total' => 23,
                    'rate' => 119.1,
                    'light' => 3,
                    'serious' => 5,
                    'v_serious' => 2,
                    'preventable' => 5,
                    'detected' => 17,
                    'cyber' => 1,
                    'solved' => 75.3
                ],
                [
                    'name' => 'Yangiyer shahri',
                    'total' => 90,
                    'rate' => 180.8,
                    'light' => 18,
                    'serious' => 28,
                    'v_serious' => 6,
                    'preventable' => 28,
                    'detected' => 53,
                    'cyber' => 9,
                    'solved' => 76.1
                ],
                [
                    'name' => 'Oq oltin tumani',
                    'total' => 53,
                    'rate' => 92.9,
                    'light' => 13,
                    'serious' => 7,
                    'v_serious' => 4,
                    'preventable' => 20,
                    'detected' => 0,
                    'cyber' => 1,
                    'solved' => 75.8
                ],
                [
                    'name' => 'Boyovut tumani',
                    'total' => 89,
                    'rate' => 62.2,
                    'light' => 27,
                    'serious' => 26,
                    'v_serious' => 3,
                    'preventable' => 27,
                    'detected' => 0,
                    'cyber' => 15,
                    'solved' => 76.1
                ],
                [
                    'name' => 'Sayxunobod tumani',
                    'total' => 63,
                    'rate' => 74.5,
                    'light' => 19,
                    'serious' => 12,
                    'v_serious' => 7,
                    'preventable' => 18,
                    'detected' => 44,
                    'cyber' => 1,
                    'solved' => 78.1
                ],
                [
                    'name' => 'Guliston tumani',
                    'total' => 66,
                    'rate' => 81,
                    'light' => 24,
                    'serious' => 11,
                    'v_serious' => 6,
                    'preventable' => 16,
                    'detected' => 47,
                    'cyber' => 3,
                    'solved' => 75.4
                ],
                [
                    'name' => 'Sardoba tumani',
                    'total' => 45,
                    'rate' => 62.9,
                    'light' => 18,
                    'serious' => 3,
                    'v_serious' => 2,
                    'preventable' => 14,
                    'detected' => 0,
                    'cyber' => 32,
                    'solved' => 75.7
                ],
                [
                    'name' => 'Xovos tumani',
                    'total' => 81,
                    'rate' => 77.3,
                    'light' => 21,
                    'serious' => 22,
                    'v_serious' => 11,
                    'preventable' => 29,
                    'detected' => 0,
                    'cyber' => 4,
                    'solved' => 80.2
                ],
                [
                    'name' => 'Mirzaobod tumani',
                    'total' => 95,
                    'rate' => 113.9,
                    'light' => 24,
                    'serious' => 18,
                    'v_serious' => 12,
                    'preventable' => 26,
                    'detected' => 66,
                    'cyber' => 3,
                    'solved' => 78.3
                ],
            ],
            'samarkand' => [
                [
                    'name' => 'Samarqand shahri',
                    'total' => 1581,
                    'rate' => 260.1,
                    'light' => 229,
                    'serious' => 809,
                    'v_serious' => 121,
                    'preventable' => 383,
                    'detected' => 603,
                    'cyber' => 595,
                    'solved' => 76.1
                ],
                [
                    'name' => 'Kattaqo\'rg\'on shahri',
                    'total' => 163,
                    'rate' => 168.9,
                    'light' => 22,
                    'serious' => 81,
                    'v_serious' => 9,
                    'preventable' => 44,
                    'detected' => 72,
                    'cyber' => 47,
                    'solved' => 80.9
                ],
                [
                    'name' => 'Bulung\'ur tumani',
                    'total' => 221,
                    'rate' => 105.3,
                    'light' => 39,
                    'serious' => 119,
                    'v_serious' => 3,
                    'preventable' => 68,
                    'detected' => 61,
                    'cyber' => 92,
                    'solved' => 82
                ],
                [
                    'name' => 'Jomboy tumani',
                    'total' => 297,
                    'rate' => 150.2,
                    'light' => 47,
                    'serious' => 169,
                    'v_serious' => 8,
                    'preventable' => 76,
                    'detected' => 0,
                    'cyber' => 148,
                    'solved' => 78.3
                ],
                [
                    'name' => 'Ishtixon tumani',
                    'total' => 330,
                    'rate' => 115.3,
                    'light' => 65,
                    'serious' => 159,
                    'v_serious' => 16,
                    'preventable' => 80,
                    'detected' => 112,
                    'cyber' => 138,
                    'solved' => 82.4
                ],
                [
                    'name' => 'Kattaqo\'rg\'on tumani',
                    'total' => 444,
                    'rate' => 146.4,
                    'light' => 60,
                    'serious' => 253,
                    'v_serious' => 31,
                    'preventable' => 104,
                    'detected' => 114,
                    'cyber' => 226,
                    'solved' => 81.5
                ],
                [
                    'name' => 'Narpay tumani',
                    'total' => 254,
                    'rate' => 108.8,
                    'light' => 46,
                    'serious' => 132,
                    'v_serious' => 11,
                    'preventable' => 82,
                    'detected' => 65,
                    'cyber' => 107,
                    'solved' => 77.3
                ],
                [
                    'name' => 'Nurobod tumani',
                    'total' => 231,
                    'rate' => 137.7,
                    'light' => 45,
                    'serious' => 125,
                    'v_serious' => 10,
                    'preventable' => 76,
                    'detected' => 52,
                    'cyber' => 103,
                    'solved' => 75.6
                ],
                [
                    'name' => 'Oqdaryo tumani',
                    'total' => 261,
                    'rate' => 144.9,
                    'light' => 51,
                    'serious' => 124,
                    'v_serious' => 14,
                    'preventable' => 81,
                    'detected' => 87,
                    'cyber' => 93,
                    'solved' => 76
                ],
                [
                    'name' => 'Payariq tumani',
                    'total' => 306,
                    'rate' => 108,
                    'light' => 41,
                    'serious' => 165,
                    'v_serious' => 9,
                    'preventable' => 89,
                    'detected' => 68,
                    'cyber' => 149,
                    'solved' => 77.7
                ],
                [
                    'name' => 'Pastdarg\'om tumani',
                    'total' => 465,
                    'rate' => 116.7,
                    'light' => 63,
                    'serious' => 264,
                    'v_serious' => 17,
                    'preventable' => 162,
                    'detected' => 84,
                    'cyber' => 219,
                    'solved' => 78.6
                ],
                [
                    'name' => 'Paxtachi tumani',
                    'total' => 223,
                    'rate' => 143.7,
                    'light' => 74,
                    'serious' => 93,
                    'v_serious' => 32,
                    'preventable' => 0,
                    'detected' => 0,
                    'cyber' => 0,
                    'solved' => 80.6
                ],
                [
                    'name' => 'Samarqand tumani',
                    'total' => 400,
                    'rate' => 141.2,
                    'light' => 62,
                    'serious' => 204,
                    'v_serious' => 34,
                    'preventable' => 100,
                    'detected' => 126,
                    'cyber' => 174,
                    'solved' => 76.6
                ],
                [
                    'name' => 'Toyloq tumani',
                    'total' => 232,
                    'rate' => 100.6,
                    'light' => 36,
                    'serious' => 135,
                    'v_serious' => 13,
                    'preventable' => 58,
                    'detected' => 0,
                    'cyber' => 122,
                    'solved' => 82.6
                ],
                [
                    'name' => 'Urgut tumani',
                    'total' => 806,
                    'rate' => 138,
                    'light' => 141,
                    'serious' => 449,
                    'v_serious' => 72,
                    'preventable' => 177,
                    'detected' => 253,
                    'cyber' => 376,
                    'solved' => 79
                ],
                [
                    'name' => 'Qo\'shrabod tumani',
                    'total' => 146,
                    'rate' => 100.2,
                    'light' => 43,
                    'serious' => 64,
                    'v_serious' => 4,
                    'preventable' => 42,
                    'detected' => 43,
                    'cyber' => 61,
                    'solved' => 79.5
                ],
            ],
            'tashkent_region' => [
                [
                    'name' => 'Olmaliq shahri',
                    'total' => 431,
                    'rate' => 286,
                    'light' => 72,
                    'serious' => 249,
                    'v_serious' => 14,
                    'preventable' => 106,
                    'detected' => 125,
                    'cyber' => 200,
                    'solved' => 79.3
                ],
                [
                    'name' => 'Angren shahri',
                    'total' => 456,
                    'rate' => 242.8,
                    'light' => 56,
                    'serious' => 271,
                    'v_serious' => 15,
                    'preventable' => 138,
                    'detected' => 100,
                    'cyber' => 218,
                    'solved' => 79.7
                ],
                [
                    'name' => 'Bekobod shahri',
                    'total' => 255,
                    'rate' => 239.8,
                    'light' => 48,
                    'serious' => 125,
                    'v_serious' => 26,
                    'preventable' => 50,
                    'detected' => 107,
                    'cyber' => 98,
                    'solved' => 76.3
                ],
                [
                    'name' => 'Chirchiq shahri',
                    'total' => 427,
                    'rate' => 238.6,
                    'light' => 54,
                    'serious' => 264,
                    'v_serious' => 17,
                    'preventable' => 106,
                    'detected' => 112,
                    'cyber' => 209,
                    'solved' => 81.9
                ],
                [
                    'name' => 'Yangiyo\'l shahri',
                    'total' => 194,
                    'rate' => 218.1,
                    'light' => 21,
                    'serious' => 103,
                    'v_serious' => 15,
                    'preventable' => 51,
                    'detected' => 65,
                    'cyber' => 78,
                    'solved' => 75.5
                ],
                [
                    'name' => 'Ohangaron shahri',
                    'total' => 157,
                    'rate' => 368.1,
                    'light' => 28,
                    'serious' => 79,
                    'v_serious' => 10,
                    'preventable' => 38,
                    'detected' => 58,
                    'cyber' => 61,
                    'solved' => 75.2
                ],
                [
                    'name' => 'Nurafshon shahri',
                    'total' => 151,
                    'rate' => 257,
                    'light' => 19,
                    'serious' => 92,
                    'v_serious' => 7,
                    'preventable' => 24,
                    'detected' => 0,
                    'cyber' => 79,
                    'solved' => 75.4
                ],
                [
                    'name' => 'Oqqo\'rg\'on tumani',
                    'total' => 197,
                    'rate' => 171.7,
                    'light' => 24,
                    'serious' => 108,
                    'v_serious' => 6,
                    'preventable' => 31,
                    'detected' => 72,
                    'cyber' => 94,
                    'solved' => 75.2
                ],
                [
                    'name' => 'Quyichirchiq tumani',
                    'total' => 253,
                    'rate' => 212.9,
                    'light' => 35,
                    'serious' => 149,
                    'v_serious' => 4,
                    'preventable' => 55,
                    'detected' => 57,
                    'cyber' => 141,
                    'solved' => 76.9
                ],
                [
                    'name' => 'Ohangaron tumani',
                    'total' => 247,
                    'rate' => 216.2,
                    'light' => 50,
                    'serious' => 133,
                    'v_serious' => 16,
                    'preventable' => 91,
                    'detected' => 56,
                    'cyber' => 100,
                    'solved' => 79.8
                ],
                [
                    'name' => 'Bekobod tumani',
                    'total' => 373,
                    'rate' => 220.6,
                    'light' => 56,
                    'serious' => 229,
                    'v_serious' => 15,
                    'preventable' => 73,
                    'detected' => 94,
                    'cyber' => 206,
                    'solved' => 75.6
                ],
                [
                    'name' => 'Bo\'ka tumani',
                    'total' => 209,
                    'rate' => 151.7,
                    'light' => 29,
                    'serious' => 99,
                    'v_serious' => 20,
                    'preventable' => 64,
                    'detected' => 69,
                    'cyber' => 76,
                    'solved' => 78.3
                ],
                [
                    'name' => 'Bo\'stonliq tumani',
                    'total' => 368,
                    'rate' => 204.9,
                    'light' => 74,
                    'serious' => 144,
                    'v_serious' => 43,
                    'preventable' => 100,
                    'detected' => 165,
                    'cyber' => 103,
                    'solved' => 77.1
                ],
                [
                    'name' => 'Yuqorichirchiq tumani',
                    'total' => 366,
                    'rate' => 254.1,
                    'light' => 52,
                    'serious' => 203,
                    'v_serious' => 39,
                    'preventable' => 87,
                    'detected' => 101,
                    'cyber' => 178,
                    'solved' => 80.3
                ],
                [
                    'name' => 'Zangiota tumani',
                    'total' => 665,
                    'rate' => 346.8,
                    'light' => 66,
                    'serious' => 457,
                    'v_serious' => 31,
                    'preventable' => 126,
                    'detected' => 152,
                    'cyber' => 387,
                    'solved' => 79.5
                ],
                [
                    'name' => 'Qibray tumani',
                    'total' => 470,
                    'rate' => 257.6,
                    'light' => 42,
                    'serious' => 304,
                    'v_serious' => 22,
                    'preventable' => 74,
                    'detected' => 126,
                    'cyber' => 270,
                    'solved' => 76
                ],
                [
                    'name' => 'Piskent tumani',
                    'total' => 179,
                    'rate' => 171.7,
                    'light' => 30,
                    'serious' => 92,
                    'v_serious' => 7,
                    'preventable' => 44,
                    'detected' => 60,
                    'cyber' => 75,
                    'solved' => 75.5
                ],
                [
                    'name' => 'O\'rtachirchiq tumani',
                    'total' => 303,
                    'rate' => 212.1,
                    'light' => 55,
                    'serious' => 163,
                    'v_serious' => 14,
                    'preventable' => 73,
                    'detected' => 95,
                    'cyber' => 135,
                    'solved' => 80.6
                ],
                [
                    'name' => 'Toshkent tumani',
                    'total' => 500,
                    'rate' => 237.6,
                    'light' => 65,
                    'serious' => 340,
                    'v_serious' => 21,
                    'preventable' => 79,
                    'detected' => 137,
                    'cyber' => 284,
                    'solved' => 79.8
                ],
                [
                    'name' => 'Yangiyo\'l tumani',
                    'total' => 558,
                    'rate' => 268.7,
                    'light' => 88,
                    'serious' => 356,
                    'v_serious' => 16,
                    'preventable' => 118,
                    'detected' => 118,
                    'cyber' => 322,
                    'solved' => 76.1
                ],
                [
                    'name' => 'Chinoz tumani',
                    'total' => 283,
                    'rate' => 188.7,
                    'light' => 53,
                    'serious' => 156,
                    'v_serious' => 7,
                    'preventable' => 57,
                    'detected' => 101,
                    'cyber' => 125,
                    'solved' => 75.2
                ],
                [
                    'name' => 'Parkent tumani',
                    'total' => 293,
                    'rate' => 158.7,
                    'light' => 39,
                    'serious' => 177,
                    'v_serious' => 7,
                    'preventable' => 75,
                    'detected' => 50,
                    'cyber' => 168,
                    'solved' => 82.4
                ],
            ],
            'tashkent_city' => [
                [
                    'name' => 'Mirobod tumani',
                    'total' => 522,
                    'rate' => 317.6,
                    'light' => 89,
                    'serious' => 92,
                    'v_serious' => 127,
                    'preventable' => 187,
                    'detected' => 326,
                    'cyber' => 9,
                    'solved' => 79.5
                ],
                [
                    'name' => 'Mirzo Ulug\'bek tumani',
                    'total' => 701,
                    'rate' => 198,
                    'light' => 124,
                    'serious' => 133,
                    'v_serious' => 178,
                    'preventable' => 215,
                    'detected' => 462,
                    'cyber' => 24,
                    'solved' => 77.6
                ],
                [
                    'name' => 'Yunusobod tumani',
                    'total' => 548,
                    'rate' => 134.1,
                    'light' => 89,
                    'serious' => 110,
                    'v_serious' => 72,
                    'preventable' => 243,
                    'detected' => 297,
                    'cyber' => 8,
                    'solved' => 79.8
                ],
                [
                    'name' => 'Yakkasaroy tumani',
                    'total' => 346,
                    'rate' => 228.5,
                    'light' => 90,
                    'serious' => 41,
                    'v_serious' => 63,
                    'preventable' => 112,
                    'detected' => 229,
                    'cyber' => 5,
                    'solved' => 79.5
                ],
                [
                    'name' => 'Shayxontohur tumani',
                    'total' => 501,
                    'rate' => 131.4,
                    'light' => 97,
                    'serious' => 104,
                    'v_serious' => 83,
                    'preventable' => 200,
                    'detected' => 289,
                    'cyber' => 12,
                    'solved' => 82.9
                ],
                [
                    'name' => 'Chilonzor tumani',
                    'total' => 957,
                    'rate' => 303.6,
                    'light' => 167,
                    'serious' => 198,
                    'v_serious' => 121,
                    'preventable' => 524,
                    'detected' => 416,
                    'cyber' => 17,
                    'solved' => 80.1
                ],
                [
                    'name' => 'Sergeli tumani',
                    'total' => 416,
                    'rate' => 217.3,
                    'light' => 88,
                    'serious' => 77,
                    'v_serious' => 66,
                    'preventable' => 147,
                    'detected' => 265,
                    'cyber' => 4,
                    'solved' => 78.5
                ],
                [
                    'name' => 'Yashnobod tumani',
                    'total' => 686,
                    'rate' => 210.8,
                    'light' => 118,
                    'serious' => 174,
                    'v_serious' => 139,
                    'preventable' => 295,
                    'detected' => 372,
                    'cyber' => 19,
                    'solved' => 79.7
                ],
                [
                    'name' => 'Olmazor tumani',
                    'total' => 467,
                    'rate' => 106.8,
                    'light' => 84,
                    'serious' => 82,
                    'v_serious' => 90,
                    'preventable' => 222,
                    'detected' => 240,
                    'cyber' => 5,
                    'solved' => 78.3
                ],
                [
                    'name' => 'Uchtepa tumani',
                    'total' => 523,
                    'rate' => 164.8,
                    'light' => 97,
                    'serious' => 111,
                    'v_serious' => 104,
                    'preventable' => 188,
                    'detected' => 319,
                    'cyber' => 16,
                    'solved' => 78.7
                ],
                [
                    'name' => 'Bektemir tumani',
                    'total' => 471,
                    'rate' => 620.1,
                    'light' => 89,
                    'serious' => 59,
                    'v_serious' => 94,
                    'preventable' => 167,
                    'detected' => 299,
                    'cyber' => 5,
                    'solved' => 80.6
                ],
                [
                    'name' => 'Yangihayot tumani',
                    'total' => 360,
                    'rate' => 174.8,
                    'light' => 85,
                    'serious' => 56,
                    'v_serious' => 43,
                    'preventable' => 150,
                    'detected' => 206,
                    'cyber' => 4,
                    'solved' => 77.7
                ],
            ],
        ];

        foreach ($districts as $slug => $items) {
            $region = Region::where('slug', $slug)->first();
            if (!$region) continue;

            // Update region's accurate districts_count
            $region->update(['districts_count' => count($items)]);

            foreach ($items as $item) {
                DistrictCrime::create([
                    'region_id' => $region->id,
                    'district_name' => $item['name'],
                    'total_crimes' => $item['total'],
                    'crime_rate_per_100k' => $item['rate'],
                    'crimes_light' => $item['light'],
                    'crimes_serious' => $item['serious'],
                    'crimes_very_serious' => $item['v_serious'],
                    'preventable_total' => $item['preventable'],
                    'detected_total' => $item['detected'],
                    'cybercrime' => $item['cyber'],
                    'solved_rate' => $item['solved'],
                    'year' => 2026,
                ]);
            }
        }
    }
}
